return {
    prefix = 'Semicolon',
    chatLogs = false,
    joinLogs = false,
    cmdLogs = false,
    persistant = false,
    staff = {},
    binds = {},
    spawns = {},
    points = {},
    aliases = {},
    permissions = {},
    plugins = {},
    executor = {},
    lastCommand = {},
    history = {},
    textColor = {255, 153, 112},
    barColor = {34, 30, 28},
}